### ISSUE TITLE
Cannot get the custom message

### ISSUE THREAD

**Issue by DanielRamosAcosta** [matteodelabre/mongoose-beautiful-unique-validation#31]
I have this User schema:

```node
import mongoose from 'mongoose'
import bcrypt from 'bcrypt-nodejs'
import beautifyUnique from 'mongoose-beautiful-unique-validation'

let UserSchema = mongoose.Schema({
  email: {
    type: String,
    required: [true, 'You need an email!'],
    validate: {
      validator: v => {
        return /^[A-Za-z0-9](([_.-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([.-]?[a-zA-Z0-9]+)*).([A-Za-z]{2,})$/.test(v)
      },
      message: "{VALUE} isn't valid!",
    },
    index: {
      unique: 'That email alredy exists!' // Here!
    }
  },
  password: {
    type: String,
    required: [true, 'You need a pasword!']
  }
})

UserSchema.statics = {
  generateHash: function (password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null)
  }
}

UserSchema.methods = {
  validPassword: function (password) {
    return bcrypt.compareSync(password, this.password)
  }
}

UserSchema.plugin(beautifyUnique)

let User = mongoose.model('User', UserSchema)

export default User
```

I'm unit testing my code, and when I try to save a user with a duplicated email like this:
```node
async () => {
  let data = {
    email: 'someone@hotmail.com',
    password: 'password'
  }

  let user1 = new models.User(data)
  try {
    await user1.save()
  } catch(err) {
    console.log('user1 error')
    console.log(err)
  }
  let user2 = new models.User(data)
  try {
    await user2.save()
  } catch(err) {
    console.log('user2 error')
    console.log(err)
  }
```

I get this error object:

```
user2 error
{ ValidationError: Validator failed for path `email` with value `someone@hotmail.com`
    at MongooseError.ValidationError (C:\[...]\backend\node_modules\mongoose\lib\error\validation.js:22:11)
    at C:\[...]\backend\node_modules\mongoose-beautiful-unique-validation\index.js:99:31
    at tryCallOne (C:\[...]\backend\node_modules\promise\lib\core.js:37:12)
    at C:\[...]\backend\node_modules\promise\lib\core.js:123:15
    at flush (C:\[...]\backend\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Validation failed',
  name: 'ValidationError',
  errors:
   { email:
      { Validator failed for path `email` with value `someone@hotmail.com`
          at MongooseError.ValidatorError (C:\[...]\backend\node_modules\mongoose\lib\error\validator.js:24:11)
          at C:\[...]\backend\node_modules\mongoose-beautiful-unique-validation\index.js:89:43
          at Array.forEach (native)
          at C:\[...]\backend\node_modules\mongoose-beautiful-unique-validation\index.js:77:40
          at tryCallOne (C:\[...]\backend\node_modules\promise\lib\core.js:37:12)
          at C:\[...]\backend\node_modules\promise\lib\core.js:123:15
          at flush (C:\[...]\backend\node_modules\asap\raw.js:50:29)
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        message: 'Validator failed for path `email` with value `someone@hotmail.com`',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'Duplicate value',
        path: 'email',
        value: 'someone@hotmail.com' } } }
```

And here I can't find the message I placed in the Schema 😢

**Comment by matteodelabre** [comment]
Hello, thanks for the detailed report! Could you try replacing `index: {unique: 'message'}` with `unique: 'message'` in your schema definition?

**Comment by DanielRamosAcosta** [comment]
Yes that was it! Thanks so much 😄

**Comment by devarashetty** [comment]
One  question though , it was still sending the error as validation failed but not the exact message 

```
new collection.save(function(err){
  if(err){
     const message = err.errors.username.message // assuming username to be unique
       // now how to attach the error back to client side ?
      // I tried  (return message) and throw new Error(message) but didn't work on either of it
  
  }
}
```
