### ISSUE TITLE
TypeError for plugin

### ISSUE THREAD

**Issue by timargra** [matteodelabre/mongoose-beautiful-unique-validation#33]
Node.js@6.7.0
mongoose@4.8.6

I get the following error, when calling the plugin method for my schema:

```
TypeError: fn is not a function
    at Schema.plugin (/node_modules/mongoose/lib/schema.js:1139:3)
    at Object.<anonymous> (/app/models/user.js:211:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by matteodelabre** [comment]
Hello @timargra, sorry for the delay in answering your question. The tests successfully passed with Node.js 6.7.0 and mongoose 4.8.6 on my machine. I’m using MongoDB 3.4.6. Can you provide a minimal example of failing code, please?

**Comment by matteodelabre** [comment]
I am going to close this. @timargra, if you still encounter the problem, please feel free to re-open the issue. Please consider adding more details to your issue so that we can reproduce the bug and help you.
