### ISSUE TITLE
6.0.0 and mongoose 4.11.3

### ISSUE THREAD

**Issue by mm188200** [matteodelabre/mongoose-beautiful-unique-validation#38]
Getting an error when unique fails, it appears in the postHook function the doc is null, the error message looks correct.  Didnt dive in too much yet , see attached screen with values that cause the error.  
**Error w/ 5.1.1** 

`TypeError: Cannot use 'in' operator to search for 'collection' in null
    at beautify (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose-beautiful-unique-validation/index.js:61:22)
    at model.postHook (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose-beautiful-unique-validation/index.js:147:13)
    at next (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/kareem/index.js:149:14)
    at Kareem.execPost (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/kareem/index.js:197:3)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/lib/model.js:217:35
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/lib/model.js:150:9
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:535:20
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:669:14
    at handleCallback (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
` 
**Error with 6.0.0 (and attached image)** 

`TypeError: Cannot read property 'collection' of null
    at model.postHook (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose-beautiful-unique-validation/index.js:152:33)
    at next (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/kareem/index.js:149:14)
    at Kareem.execPost (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/kareem/index.js:197:3)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/lib/model.js:217:35
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/lib/model.js:150:9
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:535:20
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:669:14
    at handleCallback (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /Users/michaelmorris/AirTab/backend/airtab-app/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)`

<img width="1116" alt="screen shot 2017-07-18 at 11 52 38 am" src="https://user-images.githubusercontent.com/1574714/28327904-cabd6eb6-6bb2-11e7-94ce-0bb94ae61b4a.png">

**Comment by JustinLivi** [comment]
It appears that the error postHook is not being passed the doc properly in 4.11.3

Automattic/mongoose#5496

Downgrading mongoose to 4.10.8 is a temporary workaround.

**Comment by JustinLivi** [comment]
Upgrading to 4.11.4 should now resolve this issue. (It has for me)

Automattic/mongoose#5466

**Comment by matteodelabre** [comment]
I can confirm that mongoose@4.11.3 breaks this package. The next major version will recommend usage with 4.11.4 or greater to avoid any confusion. Thanks everyone!

**Comment by andreisaikouski** [comment]
Running into the same issue with mongoose@4.13.20, any suggestions?

`TypeError: Cannot use 'in' operator to search for 'collection' in null
    at beautify (/Users/andrei.saikouskiibm.com/Documents/ChatBot_Broker/Cognitive_Broker/broker-reporter/node_modules/mongoose-beautiful-unique-validation/index.js:61:22)`
